### ISSUE TITLE
Demo is too complicated

### ISSUE THREAD

**Issue by OnePieceLv** [RxSwiftCommunity/RxState#13]
hi guys:
       can provide a simple code show how to use in app？

**Comment by nazeehshoura** [comment]
@OnePieceLv What did you find complicated in the demo? Maybe I can add more documentation to that part :)

**Comment by OnePieceLv** [comment]
@nazeehshoura thank you for doing that library. I feel complicated because  I only want to know how to use this sdk and  every class what to do  in the sdk. I spent a lot of time figuring out Coordinator, Type and so on. :)

**Comment by nazeehshoura** [comment]
The repo is actually to introduce the architecture and the pod is only a [single file](https://github.com/RxSwiftCommunity/RxState/blob/development/RxState/RxState.swift) that facilitate building the architecture by providing the definition of the [architecture's components](https://github.com/RxSwiftCommunity/RxState#architecture-components).

As for `Coordinator` and `Type`, I'll try to add more documentation that explains what to do over the weekend. For now, here's briefly what they do:

**`Type`** 
------------
I’ve used the following folder structure to make navigating the project easier:
- `<Abstraction layer>` folder: Contains all the files that belong to `<Abstraction layer>`. E.g. Model.
- Inside `<Abstraction layer>` folder, there's a `Type` folder that Contains Protocols and Base Classes used by the code in the `<Abstraction layer>`.

**`Flow Coordinator`**
------------------------
`Flow Coordinator` is class that performs a navigation. The goal of it is:

1. Be able to trigger the navigation from any object within the app without requiring the object to have a delegate (a **Controller**) that can perform the navigation. 
2. Remove the code that creates the new view controller needed for the navigation from the object requesting the navigation.
3. Update the current route (Screen) that the app is at.

You can read more about flow controllers in the [article](http://merowing.info/2016/01/improve-your-ios-architecture-with-flowcontrollers/) credited to Krzysztof Zabłocki.

Thank you for your question! I'll add documentation to the parts you asked about :)

**Comment by nazeehshoura** [comment]
The repo is actually to introduce the architecture and the pod is only a [single file](https://github.com/RxSwiftCommunity/RxState/blob/development/RxState/RxState.swift) that facilitate building the architecture by providing the definition of the [architecture's components](https://github.com/RxSwiftCommunity/RxState#architecture-components).

As for `Coordinator` and `Type`, I'll try to add more documentation that explains what to do over the weekend. For now, here's briefly what they do:

**`Type`** 
------------
I’ve used the following folder structure to make navigating the project easier:
- `<Abstraction layer>` folder: Contains all the files that belong to `<Abstraction layer>`. E.g. Model.
- Inside `<Abstraction layer>` folder, there's a `Type` folder that Contains Protocols and Base Classes used by the code in the `<Abstraction layer>`.

**`Flow Coordinator`**
------------------------
`Flow Coordinator` is class that performs a navigation. The goal of it is:

1. Be able to trigger the navigation from any object within the app without requiring the object to have a delegate (a **Controller**) that can perform the navigation. 
2. Remove the code that creates the new view controller needed for the navigation from the object requesting the navigation.
3. Update the current route (Screen) that the app is at.

You can read more about flow controllers in the [article](http://merowing.info/2016/01/improve-your-ios-architecture-with-flowcontrollers/) credited to Krzysztof Zabłocki.

Thank you for your question @OnePieceLv! I'll add documentation to the parts you asked about :)
