### ISSUE TITLE
Tuple equatable extension bug

### ISSUE THREAD

**Issue by mwfire** [RxSwiftCommunity/RxState#15]
Hey guys, sorry for not investigating deeper here, but I was just flicking through the code and this seems to be a copy&paste error:

```swift
func == <T1:Equatable, T2: Equatable>(lhs: (T1, T2), rhs: (T1, T2)) -> Bool {
    return lhs.0 == lhs.0 && lhs.1 == lhs.1
}
```

which should be

```swift
func == <T1:Equatable, T2: Equatable>(lhs: (T1, T2), rhs: (T1, T2)) -> Bool {
    return lhs.0 == rhs.0 && lhs.1 == rhs.1
}
```

Can be found at

https://github.com/RxSwiftCommunity/RxState/blob/c2450bb31d17738a324f7b4abbb6b691e82b544d/RxStateExample/RxStateExample/Common/Extension/Tupe%2BEquatable.swift#L23-L26

Cheers,
Martin

**Comment by nazeehshoura** [comment]
Yup. Thanks for reporting it!
Will work on an update for the library and included a fix for this once I get some free time 😅

**Comment by mwfire** [comment]
Sure thing, and sorry for not doing a PR, busy days as well ;)

**Comment by nazeehshoura** [comment]
No worries :) Will update it this month hopefully

**Comment by chriswill0w** [comment]
@nazeehshoura has this been solved?

**Comment by nazeehshoura** [comment]
@ltblueberry0 Apologies, I'm unable to maintain this project :)
